apiVersion: v1
kind: Service
metadata:
  name: redis-slave
  labels:
    name: redis-service-slave
    app: GuestBook

spec:
  selector:
    name: redis-master-pod
    app: GuestBook
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
