apiVersion: v1
kind: Service
metadata:
  name: front-end-service
spec:
  type: NodePort
  selector:
    name: front-end
    app: GuestBook
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30000